version: '3.8'


services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes: 
      - my-db:/var/lib/mysql

  app:
    depends_on:
      - db
    build: ./app
    ports: 
      - '8080:8080'
    environment: 
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
    restart: always


volumes: 
  my-db:
